name: CI

on:
    push:
        branches: ["**"]
    pull_request:

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    run-checks:
        uses: ./.github/workflows/checks.yml
        with:
            node-version: "24"
