name: Sync meta to deno/jsr

on:
  push:
    branches: ["dev", "main"]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit || npm install

      - name: Run sync script
        run: npm run sync:meta

      - name: NOTE: This workflow is CI-only now
        run: |
          echo "This workflow runs sync:meta but does not commit changes. Use the release workflow to transiently sync before publishing."
